# version format
version: 0.1.0-pre+{build}
os: Visual Studio 2015

install:
  - appveyor DownloadFile https://github.com/GrognardsFromHell/TemplePlusDependencies/releases/download/v1.7/dependencies.7z
  - 7z x dependencies.7z

build_script:
  - ps: .\UpdateVersion.ps1
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore TemplePlus.sln
  - msbuild TemplePlus.sln /p:Configuration=Release /p:MSBuildDefines="_TP_VERSION=%APPVEYOR_BUILD_VERSION%;_TP_COMMIT=%APPVEYOR_REPO_COMMIT%;TP_RELEASE_BUILD" /verbosity:minimal

after_build:
  - ps: .\PackRelease.ps1
  - ps: .\BuildRelease.ps1
  
  # Package the symbol files
  - dump_syms.exe Release\TemplePlus.pdb > TemplePlus.sym
  - 7z a TemplePlusSymbols-%APPVEYOR_BUILD_VERSION%.zip TemplePlus.sym

  # Release Full with tools and all binaries
  - rd /s /q dist || cd .
  - mkdir dist
  - copy Release\*.exe dist
  - del dist\TemplePlus.exe
  - del dist\*Tests.exe
  - del dist\*.vshost.exe
  - copy Release\*.dll dist
  - copy dependencies\bin\*.dll dist
  - 7z a TemplePlusTools-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\dist\*

artifacts:
  - path: 'TemplePlus-*.zip'
    name: TemplePlus
  - path: 'TemplePlusSymbols-*.zip'
    name: TemplePlusSymbols
  - path: 'TemplePlusTools-*.zip'
    name: TemplePlusTools
  - path: releases-packages\*

# Deploy to GitHub Releases
# See: https://www.appveyor.com/docs/deployment/github
deploy:
  - provider: GitHub
    description: 'TODO: Release Description'
    draft: true
    prerelease: false
    auth_token:
      secure: d5CYzZnCOlX6ER56W/Rkt/DXpSL82Dr5177wRTAfNJmtG9qvcUiRX52xPju45eIS
    on:
      branch: master
      appveyor_repo_tag: true

test: off
